# Generated by Django 6.0.5 on 2026-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('en_route', 'En Ruta'), ('completed', 'Completado'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20),
        ),
    ]
