# Generated by Django 6.0.5 on 2026-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_alter_viaje_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('maintenance', 'Mantenimiento'), ('inactive', 'Inactivo')], default='active', max_length=20),
        ),
    ]
